# Generated by Django 6.0.1 on 2026-02-27 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='locationQuery',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
