# Generated by Django 6.0.1 on 2026-05-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_task_locationquery'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, unique=True)),
                ('release_notes', models.TextField()),
                ('is_mandatory', models.BooleanField(default=False)),
                ('released_at', models.DateTimeField(auto_now_add=True)),
                ('download_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-released_at'],
            },
        ),
    ]
