# Generated by Django 6.0.1 on 2026-05-07 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_appversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('work', 'Work'), ('home', 'Home'), ('school', 'School'), ('gym', 'Gym')], max_length=40)),
                ('value', models.CharField(max_length=255)),
                ('coords_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('coords_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('confidence', models.FloatField(default=1.0)),
                ('source', models.CharField(default='user', max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contexts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='usercontext',
            constraint=models.UniqueConstraint(fields=('user', 'key'), name='unique_user_context_key'),
        ),
    ]
