# Generated by Copilot for nearby places support

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_usercontext'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='coords_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='coords_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
